# Categorias
categories = {
  "Frutas" => [
    { name: "Maçã" },
    { name: "Banana Prata" },
    { name: "Laranja Pera" },
    { name: "Uva Niágara" },
    { name: "Morango" },
    { name: "Abacaxi" },
    { name: "Mamão Papaya" },
    { name: "Manga Palmer" },
    { name: "Melancia" },
    { name: "Limão Tahiti" },
    { name: "Goiaba" },
    { name: "Maracujá" },
    { name: "Pêra Williams" },
    { name: "Kiwi" },
    { name: "Ameixa" },
    { name: "Caqui" },
    { name: "Carambola" },
    { name: "Jabuticaba" },
    { name: "Pitaya" },
    { name: "Romã" },
    { name: "Figo" },
    { name: "Pêssego" },
    { name: "Nectarina" },
    { name: "Mexerica" },
    { name: "Acerola" },
    { name: "Graviola" },
    { name: "Jaca" },
    { name: "Uva Passa" },
    { name: "Uva Thompson" },
    { name: "Uva Rubi" },
    { name: "Amora" },
    { name: "Framboesa" },
    { name: "Mirtilo" },
    { name: "Lichia" },
    { name: "Tangerina" },
    { name: "Caju" },
    { name: "Jambo" },
    { name: "Seriguela" },
    { name: "Mangaba" },
    { name: "Umbu" },
    { name: "Uva Crimson" },
    { name: "Uva Itália" },
    { name: "Uva Benitaka" },
    { name: "Atemoia" },
    { name: "Fruta do Conde" },
    { name: "Abacate" },
    { name: "Banana Nanica" },
    { name: "Banana da Terra" },
    { name: "Cupuaçu" },
    { name: "Bacuri" },
    { name: "Pequi" },
    { name: "Araçá" },
    { name: "Cambucá" },
    { name: "Guabiroba" },
    { name: "Jamelão" }
  ],
  "Vegetais" => [
    { name: "Cenoura" },
    { name: "Brócolis" },
    { name: "Couve" },
    { name: "Batata" },
    { name: "Tomate" },
    { name: "Cebola" },
    { name: "Pimentão" },
    { name: "Alho" },
    { name: "Abobrinha" },
    { name: "Mandioca" },
    { name: "Batata Doce" },
    { name: "Jiló" },
    { name: "Quiabo" },
    { name: "Chuchu" },
    { name: "Berinjela" },
    { name: "Pepino" },
    { name: "Vagem" },
    { name: "Beterraba" },
    { name: "Inhame" },
    { name: "Maxixe" },
    { name: "Nabo" },
    { name: "Abóbora" },
    { name: "Milho Verde" },
    { name: "Ervilha" },
    { name: "Palmito" },
    { name: "Aspargos" },
    { name: "Alcachofra" },
    { name: "Cogumelos" },
    { name: "Rabanete" }
  ],
  "Laticínios" => [
    { name: "Leite Integral" },
    { name: "Queijo Mussarela" },
    { name: "Queijo Prato" },
    { name: "Requeijão" },
    { name: "Iogurte Natural" },
    { name: "Manteiga" },
    { name: "Leite Condensado" },
    { name: "Creme de Leite" },
    { name: "Queijo Coalho" },
    { name: "Queijo Minas" },
    { name: "Ricota" },
    { name: "Cream Cheese" },
    { name: "Leite Desnatado" },
    { name: "Iogurte Grego" },
    { name: "Leite Fermentado" },
    { name: "Queijo Cottage" },
    { name: "Iogurte de Frutas" },
    { name: "Queijo Provolone" },
    { name: "Queijo Gorgonzola" },
    { name: "Leite Semi-Desnatado" }
  ],
  "Padaria" => [
    { name: "Pão Francês" },
    { name: "Pão de Forma" },
    { name: "Pão de Queijo" },
    { name: "Broa de Milho" },
    { name: "Bisnaguinha" },
    { name: "Pão Integral" },
    { name: "Croissant" },
    { name: "Sonho" },
    { name: "Pão Australiano" },
    { name: "Pão de Batata" },
    { name: "Rosca Doce" },
    { name: "Baguete" },
    { name: "Pão de Centeio" },
    { name: "Pão de Milho" },
    { name: "Pão Doce" },
    { name: "Pão de Hambúrguer" },
    { name: "Pão de Hot Dog" },
    { name: "Pão Sírio" },
    { name: "Pão de Leite" },
    { name: "Pão Italiano" }
  ],
  "Carnes" => [
    { name: "Peito de Frango" },
    { name: "Carne Moída" },
    { name: "Picanha" },
    { name: "Costela" },
    { name: "Linguiça" },
    { name: "Bacon" },
    { name: "Alcatra" },
    { name: "Contra Filé" },
    { name: "Cupim" },
    { name: "Maminha" },
    { name: "Patinho" },
    { name: "Acém" },
    { name: "Músculo" },
    { name: "Fraldinha" },
    { name: "Filé Mignon" },
    { name: "Coxa de Frango" },
    { name: "Asa de Frango" },
    { name: "Costela Suína" },
    { name: "Pernil Suíno" },
    { name: "Lombo Suíno" },
    { name: "Coxinha da Asa" },
    { name: "Sobrecoxa" },
    { name: "Fígado" },
    { name: "Moela" },
    { name: "Coração de Frango" },
    { name: "Bisteca Suína" },
    { name: "Paleta" },
    { name: "Lagarto" },
    { name: "Capa de Filé" },
    { name: "Ponta de Peito" }
  ],
  "Frutos do Mar" => [
    { name: "Tilápia" },
    { name: "Salmão" },
    { name: "Camarão" },
    { name: "Bacalhau" },
    { name: "Merluza" },
    { name: "Pescada" },
    { name: "Sardinha" },
    { name: "Atum" },
    { name: "Polvo" },
    { name: "Lula" },
    { name: "Mexilhão" },
    { name: "Robalo" },
    { name: "Dourado" },
    { name: "Pintado" },
    { name: "Panga" },
    { name: "Camarão Seco" },
    { name: "Anchova" },
    { name: "Corvina" },
    { name: "Linguado" },
    { name: "Namorado" },
    { name: "Tainha" },
    { name: "Cavala" },
    { name: "Badejo" },
    { name: "Vermelho" },
    { name: "Pescadinha" }
  ],
  "Despensa" => [
    { name: "Arroz" },
    { name: "Feijão Carioca" },
    { name: "Macarrão Espaguete" },
    { name: "Farinha de Trigo" },
    { name: "Farinha de Mandioca" },
    { name: "Azeite Extra Virgem" },
    { name: "Óleo de Soja" },
    { name: "Açúcar" },
    { name: "Sal" },
    { name: "Fubá" },
    { name: "Extrato de Tomate" },
    { name: "Feijão Preto" },
    { name: "Macarrão Parafuso" },
    { name: "Farinha de Rosca" },
    { name: "Milho de Pipoca" },
    { name: "Caldo de Galinha" },
    { name: "Tempero Completo" },
    { name: "Vinagre" },
    { name: "Molho de Soja" },
    { name: "Maionese" },
    { name: "Ketchup" },
    { name: "Mostarda" },
    { name: "Farinha de Milho" },
    { name: "Amido de Milho" },
    { name: "Fermento em Pó" },
    { name: "Fermento Biológico" },
    { name: "Creme de Leite" },
    { name: "Leite Condensado" },
    { name: "Sardinha em Lata" },
    { name: "Atum em Lata" },
    { name: "Ervilha em Lata" },
    { name: "Milho em Lata" },
    { name: "Seleta de Legumes" },
    { name: "Molho de Tomate" },
    { name: "Azeite de Dendê" }
  ],
  "Bebidas" => [
    { name: "Café em Pó" },
    { name: "Chá Mate" },
    { name: "Suco de Laranja" },
    { name: "Água Mineral" },
    { name: "Refrigerante" },
    { name: "Cerveja" },
    { name: "Leite de Coco" },
    { name: "Água de Coco" },
    { name: "Vinho Tinto" },
    { name: "Vinho Branco" },
    { name: "Espumante" },
    { name: "Vodka" },
    { name: "Whisky" },
    { name: "Cachaça" },
    { name: "Energético" },
    { name: "Suco de Uva" },
    { name: "Suco de Maracujá" },
    { name: "Chá Verde" },
    { name: "Café Solúvel" },
    { name: "Gin" },
    { name: "Prosecco" },
    { name: "Conhaque" },
    { name: "Licor" },
    { name: "Rum" },
    { name: "Suco Natural" },
    { name: "Suco Concentrado" },
    { name: "Chá Preto" },
    { name: "Chá de Camomila" },
    { name: "Água Tônica" },
    { name: "Sidra" }
  ],
  "Produtos de Limpeza" => [
    { name: "Detergente" },
    { name: "Sabão em Pó" },
    { name: "Água Sanitária" },
    { name: "Desinfetante" },
    { name: "Amaciante" },
    { name: "Álcool 70%" },
    { name: "Sabão em Barra" },
    { name: "Multiuso" },
    { name: "Lustra Móveis" },
    { name: "Limpa Vidros" },
    { name: "Cera Líquida" },
    { name: "Saponáceo" },
    { name: "Removedor" },
    { name: "Luvas de Borracha" },
    { name: "Esponja" },
    { name: "Pano de Chão" },
    { name: "Vassoura" },
    { name: "Rodo" },
    { name: "Pá de Lixo" },
    { name: "Saco de Lixo" },
    { name: "Limpa Alumínio" },
    { name: "Desengordurante" },
    { name: "Alvejante" },
    { name: "Amaciante de Roupas" },
    { name: "Sabonete Líquido" },
    { name: "Purificador de Ar" },
    { name: "Inseticida" },
    { name: "Desentupidor" },
    { name: "Escova de Limpeza" },
    { name: "Balde" }
  ],
  "Cuidados Pessoais" => [
    { name: "Shampoo" },
    { name: "Condicionador" },
    { name: "Pasta de Dente" },
    { name: "Sabonete" },
    { name: "Desodorante" },
    { name: "Papel Higiênico" },
    { name: "Absorvente" },
    { name: "Escova de Dentes" },
    { name: "Fio Dental" },
    { name: "Creme de Barbear" },
    { name: "Aparelho de Barbear" },
    { name: "Hidratante Corporal" },
    { name: "Protetor Solar" },
    { name: "Algodão" },
    { name: "Cotonete" },
    { name: "Lenço Umedecido" },
    { name: "Creme para Pentear" },
    { name: "Antitranspirante" },
    { name: "Enxaguante Bucal" },
    { name: "Sabonete Líquido" },
    { name: "Máscara Facial" },
    { name: "Esmalte" },
    { name: "Acetona" },
    { name: "Lixa de Unha" },
    { name: "Cortador de Unha" },
    { name: "Pinça" },
    { name: "Escova de Cabelo" },
    { name: "Pente" },
    { name: "Gel para Cabelo" },
    { name: "Tintura para Cabelo" },
    { name: "Água Oxigenada" },
    { name: "Talco" },
    { name: "Pomada" },
    { name: "Creme para Mãos" },
    { name: "Creme para Pés" },
    { name: "Removedor de Maquiagem" },
    { name: "Base Facial" },
    { name: "Batom" },
    { name: "Rímel" },
    { name: "Delineador" }
  ],
  "Hortifruti" => [
    { name: "Alface" },
    { name: "Rúcula" },
    { name: "Agrião" },
    { name: "Coentro" },
    { name: "Salsa" },
    { name: "Cebolinha" },
    { name: "Alface Americana" },
    { name: "Espinafre" },
    { name: "Repolho" },
    { name: "Acelga" },
    { name: "Chicória" },
    { name: "Hortelã" },
    { name: "Manjericão Fresco" },
    { name: "Alface Roxa" },
    { name: "Couve-Flor" },
    { name: "Rabanete" },
    { name: "Nabo" },
    { name: "Alface Crespa" },
    { name: "Couve Manteiga" },
    { name: "Mostarda" },
    { name: "Almeirão" },
    { name: "Broto de Feijão" },
    { name: "Broto de Alfafa" },
    { name: "Endívia" },
    { name: "Escarola" },
    { name: "Salsão" },
    { name: "Brócolis Japonês" },
    { name: "Couve de Bruxelas" },
    { name: "Alho-Poró" },
    { name: "Gengibre" }
  ],
  "Congelados" => [
    { name: "Pão de Queijo Congelado" },
    { name: "Lasanha" },
    { name: "Pizza" },
    { name: "Hambúrguer" },
    { name: "Batata Frita" },
    { name: "Polpa de Fruta" },
    { name: "Nuggets" },
    { name: "Coxinha" },
    { name: "Pão de Alho" },
    { name: "Legumes Congelados" },
    { name: "Açaí" },
    { name: "Sorvete" },
    { name: "Kibe" },
    { name: "Risoles" },
    { name: "Empada" },
    { name: "Pastel" },
    { name: "Bolinho de Bacalhau" },
    { name: "Escondidinho" },
    { name: "Yakisoba" },
    { name: "Peixe Empanado" },
    { name: "Massa para Pastel" },
    { name: "Torta Congelada" },
    { name: "Aipim Congelado" },
    { name: "Camarão Congelado" },
    { name: "Polenta Palito" }
  ],
  "Doces e Sobremesas" => [
    { name: "Chocolate" },
    { name: "Paçoca" },
    { name: "Pé de Moleque" },
    { name: "Goiabada" },
    { name: "Doce de Leite" },
    { name: "Cocada" },
    { name: "Brigadeiro" },
    { name: "Pudim" },
    { name: "Gelatina" },
    { name: "Bananada" },
    { name: "Mariola" },
    { name: "Rapadura" },
    { name: "Doce de Abóbora" },
    { name: "Beijinho" },
    { name: "Cajuzinho" },
    { name: "Maria Mole" },
    { name: "Quebra-Queixo" },
    { name: "Doce de Mamão" },
    { name: "Suspiro" },
    { name: "Quindim" },
    { name: "Doce de Caju" },
    { name: "Ambrosia" },
    { name: "Doce de Figo" },
    { name: "Olho de Sogra" },
    { name: "Manjar" },
    { name: "Doce de Batata Doce" },
    { name: "Pamonha Doce" },
    { name: "Pé de Moça" },
    { name: "Doce de Cidra" },
    { name: "Bolo de Rolo" },
    { name: "Doce de Leite Pastoso" },
    { name: "Bombom" },
    { name: "Trufa" },
    { name: "Mousse" },
    { name: "Pavê" }
  ],
  "Temperos e Condimentos" => [
    { name: "Pimenta do Reino" },
    { name: "Cominho" },
    { name: "Colorau" },
    { name: "Orégano" },
    { name: "Louro" },
    { name: "Curry" },
    { name: "Páprica" },
    { name: "Manjericão" },
    { name: "Alecrim" },
    { name: "Açafrão" },
    { name: "Canela em Pó" },
    { name: "Cravo" },
    { name: "Noz-Moscada" },
    { name: "Pimenta Calabresa" },
    { name: "Gengibre" },
    { name: "Coentro em Grãos" },
    { name: "Pimenta Branca" },
    { name: "Tomilho" },
    { name: "Sálvia" },
    { name: "Cardamomo" },
    { name: "Pimenta Malagueta" },
    { name: "Pimenta Dedo de Moça" },
    { name: "Pimenta de Cheiro" },
    { name: "Pimenta Biquinho" },
    { name: "Urucum" },
    { name: "Chimichurri" },
    { name: "Pimenta Síria" },
    { name: "Tempero Baiano" },
    { name: "Ervas Finas" },
    { name: "Pimenta Rosa" },
    { name: "Zimbro" },
    { name: "Mostarda em Grãos" },
    { name: "Gergelim" },
    { name: "Páprica Defumada" },
    { name: "Pimenta Caiena" }
  ],
  "Produtos para Churrasco" => [
    { name: "Carvão" },
    { name: "Sal Grosso" },
    { name: "Farofa Pronta" },
    { name: "Pão de Alho" },
    { name: "Espetos" },
    { name: "Acendedor" },
    { name: "Papel Alumínio" },
    { name: "Guardanapo" },
    { name: "Pratos Descartáveis" },
    { name: "Talheres Descartáveis" },
    { name: "Grelha" },
    { name: "Pegador" },
    { name: "Faca para Churrasco" },
    { name: "Tábua de Corte" },
    { name: "Avental" },
    { name: "Luva Térmica" },
    { name: "Limpa Grelha" },
    { name: "Carvão de Qualidade Premium" },
    { name: "Churrasqueira Portátil" },
    { name: "Termômetro para Carne" },
    { name: "Escova para Limpeza" },
    { name: "Acendedor Elétrico" },
    { name: "Espeto Giratório" },
    { name: "Kit Churrasco" },
    { name: "Grelha Antiaderente" }
  ],
  "Produtos Orientais" => [
    { name: "Shoyu" },
    { name: "Missô" },
    { name: "Wasabi" },
    { name: "Gengibre em Conserva" },
    { name: "Alga Nori" },
    { name: "Arroz para Sushi" },
    { name: "Molho Tarê" },
    { name: "Sake" },
    { name: "Óleo de Gergelim" },
    { name: "Macarrão Lámen" },
    { name: "Tempurá" },
    { name: "Tofu" },
    { name: "Karê" },
    { name: "Gohan" },
    { name: "Hashi" },
    { name: "Wakame" },
    { name: "Gergelim" },
    { name: "Molho Ponzu" },
    { name: "Vinagre de Arroz" },
    { name: "Chá Verde Matcha" },
    { name: "Molho Teriyaki" },
    { name: "Tempero para Yakisoba" },
    { name: "Macarrão Udon" },
    { name: "Macarrão Soba" },
    { name: "Panko" },
    { name: "Furikake" },
    { name: "Kombu" },
    { name: "Katsuobushi" },
    { name: "Molho Yakitori" },
    { name: "Gyoza" },
    { name: "Tempero Shichimi" },
    { name: "Saquê Culinário" },
    { name: "Pasta de Amendoim" },
    { name: "Pasta de Curry" },
    { name: "Molho Tonkatsu" }
  ],
  "Produtos Fitness" => [
    { name: "Whey Protein" },
    { name: "BCAA" },
    { name: "Creatina" },
    { name: "Barra de Proteína" },
    { name: "Pasta de Amendoim" },
    { name: "Albumina" },
    { name: "Granola" },
    { name: "Aveia" },
    { name: "Quinoa" },
    { name: "Chia" },
    { name: "Linhaça" },
    { name: "Goji Berry" },
    { name: "Proteína Vegetal" },
    { name: "Colágeno" },
    { name: "Glutamina" },
    { name: "Pré-Treino" },
    { name: "Multivitamínico" },
    { name: "Barra de Cereal" },
    { name: "Shake" },
    { name: "Termogênico" },
    { name: "Cápsulas de Ômega 3" },
    { name: "Castanhas" },
    { name: "Iogurte Proteico" },
    { name: "Bebida de Arroz" },
    { name: "Biscoito Proteico" }
  ],
  "Produtos Veganos" => [
    { name: "Leite de Amêndoas" },
    { name: "Leite de Soja" },
    { name: "Tofu" },
    { name: "Seitan" },
    { name: "Tempeh" },
    { name: "Proteína de Ervilha" },
    { name: "Leite de Aveia" },
    { name: "Queijo Vegano" },
    { name: "Hambúrguer Vegetal" },
    { name: "Nutritional Yeast" },
    { name: "Leite de Coco" },
    { name: "Maionese Vegana" },
    { name: "Requeijão Vegano" },
    { name: "Creme de Leite Vegano" },
    { name: "Manteiga Vegetal" },
    { name: "Salsicha Vegana" },
    { name: "Nuggets Vegano" },
    { name: "Atum Vegetal" },
    { name: "Mel de Agave" },
    { name: "Leite de Castanha" },
    { name: "Cream Cheese Vegano" },
    { name: "Sorvete Vegano" },
    { name: "Chocolate Vegano" },
    { name: "Iogurte Vegano" },
    { name: "Mortadela Vegana" }
  ],
  "Produtos Zero" => [
    { name: "Leite Zero Lactose" },
    { name: "Iogurte Zero Lactose" },
    { name: "Queijo Zero Lactose" },
    { name: "Requeijão Zero Lactose" },
    { name: "Manteiga Zero Lactose" },
    { name: "Creme de Leite Zero Lactose" },
    { name: "Chocolate Zero Lactose" },
    { name: "Sorvete Zero Lactose" },
    { name: "Pão sem Glúten" },
    { name: "Macarrão sem Glúten" },
    { name: "Biscoito sem Glúten" },
    { name: "Farinha de Arroz" },
    { name: "Farinha de Amêndoas" },
    { name: "Granola sem Glúten" },
    { name: "Bolo sem Glúten" },
    { name: "Tapioca" },
    { name: "Adoçante" },
    { name: "Refrigerante Zero" },
    { name: "Gelatina Zero" },
    { name: "Chocolate Zero Açúcar" },
    { name: "Biscoito Zero Açúcar" },
    { name: "Suco Zero Açúcar" },
    { name: "Bala Zero Açúcar" },
    { name: "Geleia Zero Açúcar" },
    { name: "Achocolatado Zero Lactose" }
  ],
  "Produtos para Pets" => [
    { name: "Ração para Cães" },
    { name: "Ração para Gatos" },
    { name: "Petiscos" },
    { name: "Areia para Gatos" },
    { name: "Shampoo Pet" },
    { name: "Brinquedos" },
    { name: "Coleira" },
    { name: "Tapete Higiênico" },
    { name: "Escova" },
    { name: "Comedouro" },
    { name: "Ração Úmida" },
    { name: "Antipulgas" },
    { name: "Vermífugo" },
    { name: "Caixa de Transporte" },
    { name: "Cama Pet" },
    { name: "Arranhador" },
    { name: "Guia" },
    { name: "Bebedouro" },
    { name: "Sanitário para Gatos" },
    { name: "Pente" },
    { name: "Cortador de Unhas" },
    { name: "Roupas Pet" },
    { name: "Vitaminas" },
    { name: "Porta Ração" },
    { name: "Ossos para Cães" }
  ]
}

# Seeding the categories and items
categories.each do |category_name, items|
  category = Category.find_or_create_by!(name: category_name)
  items.each do |item_attributes|
    category.items.find_or_create_by!(name: item_attributes[:name])
  end
end

puts "Seeding complete!"
