# Categorias
categories = {
  "Frutas" => [
    { name: "Maçã" },
    { name: "Banana Prata" },
    { name: "Laranja Pera" },
    { name: "Uva Niágara" },
    { name: "Morango" },
    { name: "Abacaxi" },
    { name: "Mamão Papaya" },
    { name: "Manga Palmer" },
    { name: "Melancia" },
    { name: "Limão Tahiti" },
    { name: "Goiaba" },
    { name: "Maracujá" },
    { name: "Pêra Williams" },
    { name: "Kiwi" },
    { name: "Ameixa" },
    { name: "Caqui" },
    { name: "Carambola" },
    { name: "Jabuticaba" },
    { name: "Pitaya" },
    { name: "Romã" },
    { name: "Figo" },
    { name: "Pêssego" },
    { name: "Nectarina" },
    { name: "Mexerica" },
    { name: "Acerola" },
    { name: "Graviola" },
    { name: "Jaca" }
  ],
  "Vegetais" => [
    { name: "Cenoura" },
    { name: "Brócolis" },
    { name: "Couve" },
    { name: "Batata" },
    { name: "Tomate" },
    { name: "Cebola" },
    { name: "Pimentão" },
    { name: "Alho" },
    { name: "Abobrinha" },
    { name: "Mandioca" },
    { name: "Batata Doce" },
    { name: "Jiló" },
    { name: "Quiabo" },
    { name: "Chuchu" },
    { name: "Berinjela" },
    { name: "Pepino" },
    { name: "Vagem" },
    { name: "Beterraba" },
    { name: "Inhame" },
    { name: "Maxixe" }
  ],
  "Laticínios" => [
    { name: "Leite Integral" },
    { name: "Queijo Mussarela" },
    { name: "Queijo Prato" },
    { name: "Requeijão" },
    { name: "Iogurte Natural" },
    { name: "Manteiga" },
    { name: "Leite Condensado" },
    { name: "Creme de Leite" },
    { name: "Queijo Coalho" },
    { name: "Queijo Minas" },
    { name: "Ricota" },
    { name: "Cream Cheese" },
    { name: "Leite Desnatado" },
    { name: "Iogurte Grego" }
  ],
  "Padaria" => [
    { name: "Pão Francês" },
    { name: "Pão de Forma" },
    { name: "Pão de Queijo" },
    { name: "Broa de Milho" },
    { name: "Bisnaguinha" },
    { name: "Pão Integral" },
    { name: "Croissant" },
    { name: "Sonho" },
    { name: "Pão Australiano" },
    { name: "Pão de Batata" },
    { name: "Rosca Doce" },
    { name: "Baguete" }
  ],
  "Carnes" => [
    { name: "Peito de Frango" },
    { name: "Carne Moída" },
    { name: "Picanha" },
    { name: "Costela" },
    { name: "Linguiça" },
    { name: "Bacon" },
    { name: "Alcatra" },
    { name: "Contra Filé" },
    { name: "Cupim" },
    { name: "Maminha" },
    { name: "Patinho" },
    { name: "Acém" },
    { name: "Músculo" },
    { name: "Fraldinha" },
    { name: "Filé Mignon" },
    { name: "Coxa de Frango" },
    { name: "Asa de Frango" },
    { name: "Costela Suína" },
    { name: "Pernil Suíno" },
    { name: "Lombo Suíno" }
  ],
  "Frutos do Mar" => [
    { name: "Tilápia" },
    { name: "Salmão" },
    { name: "Camarão" },
    { name: "Bacalhau" },
    { name: "Merluza" },
    { name: "Pescada" },
    { name: "Sardinha" },
    { name: "Atum" },
    { name: "Polvo" },
    { name: "Lula" },
    { name: "Mexilhão" },
    { name: "Robalo" },
    { name: "Dourado" },
    { name: "Pintado" },
    { name: "Panga" }
  ],
  "Despensa" => [
    { name: "Arroz" },
    { name: "Feijão Carioca" },
    { name: "Macarrão Espaguete" },
    { name: "Farinha de Trigo" },
    { name: "Farinha de Mandioca" },
    { name: "Azeite Extra Virgem" },
    { name: "Óleo de Soja" },
    { name: "Açúcar" },
    { name: "Sal" },
    { name: "Fubá" },
    { name: "Extrato de Tomate" },
    { name: "Feijão Preto" },
    { name: "Macarrão Parafuso" },
    { name: "Farinha de Rosca" },
    { name: "Milho de Pipoca" },
    { name: "Caldo de Galinha" },
    { name: "Tempero Completo" },
    { name: "Vinagre" },
    { name: "Molho de Soja" },
    { name: "Maionese" },
    { name: "Ketchup" },
    { name: "Mostarda" }
  ],
  "Bebidas" => [
    { name: "Café em Pó" },
    { name: "Chá Mate" },
    { name: "Suco de Laranja" },
    { name: "Água Mineral" },
    { name: "Refrigerante" },
    { name: "Cerveja" },
    { name: "Leite de Coco" },
    { name: "Água de Coco" },
    { name: "Vinho Tinto" },
    { name: "Vinho Branco" },
    { name: "Espumante" },
    { name: "Vodka" },
    { name: "Whisky" },
    { name: "Cachaça" },
    { name: "Energético" },
    { name: "Suco de Uva" },
    { name: "Suco de Maracujá" },
    { name: "Chá Verde" },
    { name: "Café Solúvel" },
    { name: "Gin" }
  ],
  "Produtos de Limpeza" => [
    { name: "Detergente" },
    { name: "Sabão em Pó" },
    { name: "Água Sanitária" },
    { name: "Desinfetante" },
    { name: "Amaciante" },
    { name: "Álcool 70%" },
    { name: "Sabão em Barra" },
    { name: "Multiuso" },
    { name: "Lustra Móveis" },
    { name: "Limpa Vidros" },
    { name: "Cera Líquida" },
    { name: "Saponáceo" },
    { name: "Removedor" },
    { name: "Luvas de Borracha" },
    { name: "Esponja" },
    { name: "Pano de Chão" },
    { name: "Vassoura" },
    { name: "Rodo" },
    { name: "Pá de Lixo" },
    { name: "Saco de Lixo" }
  ],
  "Cuidados Pessoais" => [
    { name: "Shampoo" },
    { name: "Condicionador" },
    { name: "Pasta de Dente" },
    { name: "Sabonete" },
    { name: "Desodorante" },
    { name: "Papel Higiênico" },
    { name: "Absorvente" },
    { name: "Escova de Dentes" },
    { name: "Fio Dental" },
    { name: "Creme de Barbear" },
    { name: "Aparelho de Barbear" },
    { name: "Hidratante Corporal" },
    { name: "Protetor Solar" },
    { name: "Algodão" },
    { name: "Cotonete" },
    { name: "Lenço Umedecido" },
    { name: "Creme para Pentear" },
    { name: "Antitranspirante" },
    { name: "Enxaguante Bucal" },
    { name: "Sabonete Líquido" }
  ],
  "Hortifruti" => [
    { name: "Alface" },
    { name: "Rúcula" },
    { name: "Agrião" },
    { name: "Coentro" },
    { name: "Salsa" },
    { name: "Cebolinha" },
    { name: "Alface Americana" },
    { name: "Espinafre" },
    { name: "Repolho" },
    { name: "Acelga" },
    { name: "Chicória" },
    { name: "Hortelã" },
    { name: "Manjericão Fresco" },
    { name: "Alface Roxa" },
    { name: "Couve-Flor" },
    { name: "Rabanete" },
    { name: "Nabo" }
  ],
  "Congelados" => [
    { name: "Pão de Queijo Congelado" },
    { name: "Lasanha" },
    { name: "Pizza" },
    { name: "Hambúrguer" },
    { name: "Batata Frita" },
    { name: "Polpa de Fruta" },
    { name: "Nuggets" },
    { name: "Coxinha" },
    { name: "Pão de Alho" },
    { name: "Legumes Congelados" },
    { name: "Açaí" },
    { name: "Sorvete" }
  ],
  "Doces e Sobremesas" => [
    { name: "Chocolate" },
    { name: "Paçoca" },
    { name: "Pé de Moleque" },
    { name: "Goiabada" },
    { name: "Doce de Leite" },
    { name: "Cocada" },
    { name: "Brigadeiro" },
    { name: "Pudim" },
    { name: "Gelatina" },
    { name: "Bananada" },
    { name: "Mariola" },
    { name: "Rapadura" },
    { name: "Doce de Abóbora" },
    { name: "Beijinho" },
    { name: "Cajuzinho" },
    { name: "Maria Mole" },
    { name: "Quebra-Queixo" },
    { name: "Doce de Mamão" },
    { name: "Suspiro" },
    { name: "Quindim" }
  ],
  "Temperos e Condimentos" => [
    { name: "Pimenta do Reino" },
    { name: "Cominho" },
    { name: "Colorau" },
    { name: "Orégano" },
    { name: "Louro" },
    { name: "Curry" },
    { name: "Páprica" },
    { name: "Manjericão" },
    { name: "Alecrim" },
    { name: "Açafrão" },
    { name: "Canela em Pó" },
    { name: "Cravo" },
    { name: "Noz-Moscada" },
    { name: "Pimenta Calabresa" },
    { name: "Gengibre" },
    { name: "Coentro em Grãos" },
    { name: "Pimenta Branca" },
    { name: "Tomilho" },
    { name: "Sálvia" },
    { name: "Cardamomo" }
  ],
  "Produtos para Churrasco" => [
    { name: "Carvão" },
    { name: "Sal Grosso" },
    { name: "Farofa Pronta" },
    { name: "Pão de Alho" },
    { name: "Espetos" },
    { name: "Acendedor" },
    { name: "Papel Alumínio" },
    { name: "Guardanapo" },
    { name: "Pratos Descartáveis" },
    { name: "Talheres Descartáveis" }
  ],
  "Produtos Orientais" => [
    { name: "Shoyu" },
    { name: "Missô" },
    { name: "Wasabi" },
    { name: "Gengibre em Conserva" },
    { name: "Alga Nori" },
    { name: "Arroz para Sushi" },
    { name: "Molho Tarê" },
    { name: "Sake" },
    { name: "Óleo de Gergelim" },
    { name: "Macarrão Lámen" },
    { name: "Tempurá" },
    { name: "Tofu" },
    { name: "Karê" },
    { name: "Gohan" },
    { name: "Hashi" },
    { name: "Wakame" },
    { name: "Gergelim" },
    { name: "Molho Ponzu" },
    { name: "Vinagre de Arroz" },
    { name: "Chá Verde Matcha" }
  ],
  "Produtos Mexicanos" => [
    { name: "Tortilhas" },
    { name: "Guacamole" },
    { name: "Pimenta Jalapeño" },
    { name: "Nachos" },
    { name: "Molho de Pimenta" },
    { name: "Taco Shell" },
    { name: "Frijoles" },
    { name: "Milho para Pipoca" },
    { name: "Pimenta Chipotle" },
    { name: "Molho de Queijo" },
    { name: "Tortilla Chips" },
    { name: "Salsa" },
    { name: "Pico de Gallo" },
    { name: "Chimichurri" },
    { name: "Chili em Pó" }
  ],
  "Produtos Fitness" => [
    { name: "Whey Protein" },
    { name: "BCAA" },
    { name: "Creatina" },
    { name: "Barra de Proteína" },
    { name: "Pasta de Amendoim" },
    { name: "Albumina" },
    { name: "Granola" },
    { name: "Aveia" },
    { name: "Quinoa" },
    { name: "Chia" },
    { name: "Linhaça" },
    { name: "Goji Berry" }
  ],
  "Produtos Veganos" => [
    { name: "Leite de Amêndoas" },
    { name: "Leite de Soja" },
    { name: "Tofu" },
    { name: "Seitan" },
    { name: "Tempeh" },
    { name: "Proteína de Ervilha" },
    { name: "Leite de Aveia" },
    { name: "Queijo Vegano" },
    { name: "Hambúrguer Vegetal" },
    { name: "Nutritional Yeast" }
  ],
  "Produtos Nordestinos" => [
    { name: "Cuscuz" },
    { name: "Tapioca" },
    { name: "Carne de Sol" },
    { name: "Farinha de Mandioca Grossa" },
    { name: "Azeite de Dendê" },
    { name: "Feijão Verde" },
    { name: "Queijo Coalho" },
    { name: "Manteiga de Garrafa" },
    { name: "Rapadura" },
    { name: "Charque" },
    { name: "Goma de Tapioca" },
    { name: "Camarão Seco" }
  ],
  "Produtos Mineiros" => [
    { name: "Queijo Minas Frescal" },
    { name: "Cachaça Artesanal" },
    { name: "Linguiça Mineira" },
    { name: "Feijão Tropeiro" },
    { name: "Torresmo" },
    { name: "Doce de Leite Caseiro" },
    { name: "Café Especial" },
    { name: "Farinha de Milho" },
    { name: "Lombo Defumado" },
    { name: "Geleia de Jabuticaba" },
    { name: "Queijo Canastra" },
    { name: "Pão de Queijo Congelado" }
  ],
  "Produtos Gaúchos" => [
    { name: "Erva Mate" },
    { name: "Cuia" },
    { name: "Bomba para Chimarrão" },
    { name: "Churrasco Pronto" },
    { name: "Vinho Gaúcho" },
    { name: "Salame Colonial" },
    { name: "Queijo Serrano" },
    { name: "Arroz Carreteiro" },
    { name: "Chimia" },
    { name: "Rapadura Gaúcha" }
  ],
  "Produtos Amazônicos" => [
    { name: "Açaí em Pó" },
    { name: "Castanha do Pará" },
    { name: "Cupuaçu" },
    { name: "Guaraná em Pó" },
    { name: "Tucumã" },
    { name: "Taperebá" },
    { name: "Pupunha" },
    { name: "Jambu" },
    { name: "Pirarucu Seco" },
    { name: "Farinha d'Água" }
  ],
  "Produtos Naturais" => [
    { name: "Mel Orgânico" },
    { name: "Própolis Verde" },
    { name: "Pólen" },
    { name: "Geleia Real" },
    { name: "Spirulina" },
    { name: "Clorela" },
    { name: "Kombucha" },
    { name: "Kefir" },
    { name: "Chá de Hibisco" },
    { name: "Óleo de Coco" },
    { name: "Açúcar Mascavo" },
    { name: "Stevia" }
  ],
  "Produtos Zero Lactose" => [
    { name: "Leite Zero Lactose" },
    { name: "Iogurte Zero Lactose" },
    { name: "Queijo Zero Lactose" },
    { name: "Requeijão Zero Lactose" },
    { name: "Manteiga Zero Lactose" },
    { name: "Creme de Leite Zero Lactose" },
    { name: "Chocolate Zero Lactose" },
    { name: "Sorvete Zero Lactose" }
  ],
  "Produtos Zero Glúten" => [
    { name: "Pão sem Glúten" },
    { name: "Macarrão sem Glúten" },
    { name: "Biscoito sem Glúten" },
    { name: "Farinha de Arroz" },
    { name: "Farinha de Amêndoas" },
    { name: "Granola sem Glúten" },
    { name: "Bolo sem Glúten" },
    { name: "Tapioca" }
  ],
  "Produtos Zero Açúcar" => [
    { name: "Chocolate Zero Açúcar" },
    { name: "Gelatina Zero Açúcar" },
    { name: "Biscoito Zero Açúcar" },
    { name: "Refrigerante Zero" },
    { name: "Adoçante Natural" },
    { name: "Suco Zero Açúcar" },
    { name: "Geleia Zero Açúcar" },
    { name: "Pudim Zero Açúcar" },
    { name: "Bala Zero Açúcar" },
    { name: "Chiclete Zero Açúcar" }
  ],
  "Produtos para Pets" => [
    { name: "Ração para Cães" },
    { name: "Ração para Gatos" },
    { name: "Petiscos" },
    { name: "Areia para Gatos" },
    { name: "Shampoo Pet" },
    { name: "Brinquedos" },
    { name: "Coleira" },
    { name: "Tapete Higiênico" },
    { name: "Escova" },
    { name: "Comedouro" }
  ],
  "Produtos de Jardinagem" => [
    { name: "Terra Adubada" },
    { name: "Vaso de Planta" },
    { name: "Regador" },
    { name: "Adubo" },
    { name: "Sementes" },
    { name: "Ferramentas de Jardim" },
    { name: "Inseticida Natural" },
    { name: "Substrato" },
    { name: "Pedras Decorativas" },
    { name: "Suporte para Plantas" }
  ],
  "Produtos de Papelaria" => [
    { name: "Caderno" },
    { name: "Caneta" },
    { name: "Lápis" },
    { name: "Borracha" },
    { name: "Cola" },
    { name: "Tesoura" },
    { name: "Papel Sulfite" },
    { name: "Pasta" },
    { name: "Grampeador" },
    { name: "Clips" }
  ]
}

# Seeding the categories and items
categories.each do |category_name, items|
  category = Category.find_or_create_by!(name: category_name)
  items.each do |item_attributes|
    category.items.find_or_create_by!(name: item_attributes[:name])
  end
end

puts "Seeding complete!"
